# load in memory to fast access
preload = /home/gabriel/.config/hypr/abstract.jpg

# monitor and image
wallpaper = HDMI-A-1, /home/gabriel/.config/hypr/abstract.jpg
# deactivate load screen
splash = false

# allow communication between process
ipc = off


