# load in memory to fast access
preload = ~/home/Pictures/abstract.jpg

# monitor and image
wallpaper = , /home/gabriel/Pictures/abstract.jpg

# deactivate load screen
splash = false

# allow communication between process
ipc = off


