# load in memory to fast access
preload = /home/gabriel/.config/wallpapers/stalenhag/light_blue.jpg

# monitor and image
wallpaper = HDMI-A-1, /home/gabriel/.config/wallpapers/stalenhag/light_blue.jpg
# deactivate load screen
splash = false

# allow communication between process
ipc = off

