# load in memory to fast access
preload = /home/gabriel/.config/wallpapers/dogs_lamen.jpg

# monitor and image
wallpaper = eDP-1, /home/gabriel/.config/wallpapers/dogs_lamen.jpg
# deactivate load screen
splash = false

# allow communication between process
ipc = off



